/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bookstore.ui;

import bookstore.App;
import bookstore.database.Database;
import bookstore.database.tables.*;

import java.awt.*;  
import java.awt.event.*;
import javax.swing.*;


public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main(String name, int role) {
        initComponents();
   
        this.employeeNameLabel.setText(name);
            
        int position = role;
        String sPosition = "";
        if (position == 1)
            sPosition = "Quản lí"; 
        else if (position == 2)
            sPosition = "Kiểm kho";
        else if (position == 0)
            sPosition = "Bán hàng";
            
        this.employeePositionLabel.setText(sPosition);

        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingButton = new metro.MetroButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        headhomePanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        bodyhomePanel = new javax.swing.JPanel();
        employeeButton = new metro.MetroButton();
        authorButton = new bookstore.ui.controls.MetroButton();
        categoryButton = new bookstore.ui.controls.MetroButton();
        publisherButton = new bookstore.ui.controls.MetroButton();
        bookButton = new metro.MetroButton();
        discountButton = new bookstore.ui.controls.MetroButton();
        customerButton = new bookstore.ui.controls.MetroButton();
        billButton = new bookstore.ui.controls.MetroButton();
        moneyBillButton = new bookstore.ui.controls.MetroButton();
        bookEntryButton = new bookstore.ui.controls.MetroButton();
        introductionButton = new bookstore.ui.controls.MetroButton();
        foothomePanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        employeePositionLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        employeeNameLabel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        logoutButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        switchPanel = new javax.swing.JPanel();
        employeePanel = new bookstore.ui.subpanel.EmployeePanel();
        try {
            introductionPanel = new bookstore.ui.subpanel.IntroductionPanel();
        } catch (bookstore.exceptions.DatabasePermissonErrorException e1) {
            e1.printStackTrace();
        }
        authorPanel = new bookstore.ui.subpanel.AuthorPanel();
        publisherPanel = new bookstore.ui.subpanel.PublisherPanel();
        catogeryPanel = new bookstore.ui.subpanel.CatogeryPanel();
        discountPanel = new bookstore.ui.subpanel.DiscountPanel();
        bookPanel = new bookstore.ui.subpanel.BookPanel();
        customerPanel = new bookstore.ui.subpanel.CustomerPanel();
        moneyBillPanel = new bookstore.ui.subpanel.MoneyBillPanel();
        billPanel = new bookstore.ui.subpanel.BillPanel();
        bookEntryPanel = new bookstore.ui.subpanel.BookEntryPanel();
        settingPanel1 = new bookstore.ui.subpanel.SettingPanel();

        settingButton.setBackground(new java.awt.Color(40, 60, 92));
        settingButton.setText("Cài đặt");
        settingButton.setMaximumSize(new java.awt.Dimension(400, 100));
        settingButton.setMinimumSize(new java.awt.Dimension(200, 20));
        settingButton.setPreferredSize(new java.awt.Dimension(200, 40));
        settingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setMaximumSize(new java.awt.Dimension(32000, 3200));
        mainPanel.setMinimumSize(new java.awt.Dimension(400, 300));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 450));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));

        homePanel.setBackground(new java.awt.Color(51, 51, 51));
        homePanel.setMaximumSize(new java.awt.Dimension(32000, 32867));
        homePanel.setMinimumSize(new java.awt.Dimension(100, 300));
        homePanel.setPreferredSize(new java.awt.Dimension(200, 400));
        homePanel.setLayout(new javax.swing.BoxLayout(homePanel, javax.swing.BoxLayout.PAGE_AXIS));

        headhomePanel.setBackground(new java.awt.Color(51, 51, 51));
        headhomePanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        headhomePanel.setPreferredSize(new java.awt.Dimension(200, 60));

        homeLabel.setBackground(new java.awt.Color(102, 102, 102));
        homeLabel.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\Untitled.png")); // NOI18N
        homeLabel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        homeLabel.setPreferredSize(new java.awt.Dimension(100, 50));

        org.jdesktop.layout.GroupLayout headhomePanelLayout = new org.jdesktop.layout.GroupLayout(headhomePanel);
        headhomePanel.setLayout(headhomePanelLayout);
        headhomePanelLayout.setHorizontalGroup(
            headhomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(homeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        headhomePanelLayout.setVerticalGroup(
            headhomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(homeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        homePanel.add(headhomePanel);

        bodyhomePanel.setBackground(new java.awt.Color(51, 51, 51));
        bodyhomePanel.setAlignmentX((float)0.5);
        bodyhomePanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        bodyhomePanel.setPreferredSize(new java.awt.Dimension(200, 520));
        bodyhomePanel.setLayout(new javax.swing.BoxLayout(bodyhomePanel, javax.swing.BoxLayout.PAGE_AXIS));

        employeeButton.setBackground(new java.awt.Color(51, 51, 51));
        employeeButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\customers.png")); // NOI18N
        employeeButton.setText("Nhân viên");
        employeeButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        employeeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employeeButton.setMaximumSize(new java.awt.Dimension(400, 100));
        employeeButton.setMinimumSize(new java.awt.Dimension(200, 20));
        employeeButton.setPreferredSize(new java.awt.Dimension(200, 40));
        employeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(employeeButton);

        authorButton.setBackground(new java.awt.Color(51, 51, 51));
        authorButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\authors.png")); // NOI18N
        authorButton.setText("Tác giả");
        authorButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        authorButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        authorButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        authorButton.setMaximumSize(new java.awt.Dimension(400, 100));
        authorButton.setMinimumSize(new java.awt.Dimension(200, 20));
        authorButton.setPreferredSize(new java.awt.Dimension(200, 40));
        authorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(authorButton);

        categoryButton.setBackground(new java.awt.Color(51, 51, 51));
        categoryButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\categorys.png")); // NOI18N
        categoryButton.setText("Thể loại");
        categoryButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        categoryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoryButton.setMaximumSize(new java.awt.Dimension(400, 100));
        categoryButton.setMinimumSize(new java.awt.Dimension(200, 20));
        categoryButton.setPreferredSize(new java.awt.Dimension(200, 40));
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(categoryButton);

        publisherButton.setBackground(new java.awt.Color(51, 51, 51));
        publisherButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\publishers.png")); // NOI18N
        publisherButton.setText("Nhà xuất bản");
        publisherButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        publisherButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        publisherButton.setMaximumSize(new java.awt.Dimension(400, 100));
        publisherButton.setMinimumSize(new java.awt.Dimension(200, 20));
        publisherButton.setPreferredSize(new java.awt.Dimension(210, 40));
        publisherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(publisherButton);

        bookButton.setBackground(new java.awt.Color(51, 51, 51));
        bookButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\booksicon.png")); // NOI18N
        bookButton.setText("Sách");
        bookButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        bookButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bookButton.setMaximumSize(new java.awt.Dimension(400, 100));
        bookButton.setMinimumSize(new java.awt.Dimension(200, 20));
        bookButton.setPreferredSize(new java.awt.Dimension(200, 40));
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(bookButton);

        discountButton.setBackground(new java.awt.Color(51, 51, 51));
        discountButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\sales.png")); // NOI18N
        discountButton.setText("Khuyến mãi");
        discountButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        discountButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        discountButton.setMaximumSize(new java.awt.Dimension(400, 100));
        discountButton.setMinimumSize(new java.awt.Dimension(200, 20));
        discountButton.setPreferredSize(new java.awt.Dimension(200, 40));
        discountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(discountButton);

        customerButton.setBackground(new java.awt.Color(51, 51, 51));
        customerButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\employee.png")); // NOI18N
        customerButton.setText("Khách hàng");
        customerButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        customerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerButton.setMaximumSize(new java.awt.Dimension(400, 100));
        customerButton.setMinimumSize(new java.awt.Dimension(200, 20));
        customerButton.setPreferredSize(new java.awt.Dimension(200, 40));
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(customerButton);

        billButton.setBackground(new java.awt.Color(51, 51, 51));
        billButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\bill.png")); // NOI18N
        billButton.setText("Hóa đơn");
        billButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        billButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        billButton.setMaximumSize(new java.awt.Dimension(400, 100));
        billButton.setMinimumSize(new java.awt.Dimension(200, 20));
        billButton.setPreferredSize(new java.awt.Dimension(200, 40));
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(billButton);

        moneyBillButton.setBackground(new java.awt.Color(51, 51, 51));
        moneyBillButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\billmoney.png")); // NOI18N
        moneyBillButton.setText("Phiếu thu tiền");
        moneyBillButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        moneyBillButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        moneyBillButton.setMaximumSize(new java.awt.Dimension(400, 100));
        moneyBillButton.setMinimumSize(new java.awt.Dimension(200, 20));
        moneyBillButton.setPreferredSize(new java.awt.Dimension(200, 40));
        moneyBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyBillButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(moneyBillButton);

        bookEntryButton.setBackground(new java.awt.Color(51, 51, 51));
        bookEntryButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\bookEntry.png")); // NOI18N
        bookEntryButton.setText("Phiếu nhập sách");
        bookEntryButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        bookEntryButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bookEntryButton.setMaximumSize(new java.awt.Dimension(400, 100));
        bookEntryButton.setMinimumSize(new java.awt.Dimension(200, 20));
        bookEntryButton.setPreferredSize(new java.awt.Dimension(200, 40));
        bookEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookEntryButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(bookEntryButton);

        introductionButton.setBackground(new java.awt.Color(51, 51, 51));
        introductionButton.setIcon(new javax.swing.ImageIcon("D:\\UIT\\Lap trinh java\\bookstore\\imgs\\statistics.png")); // NOI18N
        introductionButton.setText("Thống kê");
        introductionButton.setFont(new java.awt.Font("Sogoe Ui", 0, 17)); // NOI18N
        introductionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        introductionButton.setMaximumSize(new java.awt.Dimension(400, 100));
        introductionButton.setMinimumSize(new java.awt.Dimension(200, 20));
        introductionButton.setPreferredSize(new java.awt.Dimension(200, 40));
        introductionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introductionButtonActionPerformed(evt);
            }
        });
        bodyhomePanel.add(introductionButton);

        homePanel.add(bodyhomePanel);

        foothomePanel.setBackground(new java.awt.Color(51, 51, 51));
        foothomePanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        foothomePanel.setPreferredSize(new java.awt.Dimension(100, 90));
        foothomePanel.setLayout(new javax.swing.BoxLayout(foothomePanel, javax.swing.BoxLayout.PAGE_AXIS));
        foothomePanel.add(filler1);

        employeePositionLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        employeePositionLabel.setForeground(new java.awt.Color(204, 204, 255));
        employeePositionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeePositionLabel.setText("chức");
        employeePositionLabel.setAlignmentX(0.5F);
        employeePositionLabel.setFocusable(false);
        employeePositionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeePositionLabel.setMaximumSize(new java.awt.Dimension(32000, 20));
        employeePositionLabel.setMinimumSize(new java.awt.Dimension(10, 10));
        employeePositionLabel.setPreferredSize(new java.awt.Dimension(100, 55));
        foothomePanel.add(employeePositionLabel);
        foothomePanel.add(filler3);

        employeeNameLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        employeeNameLabel.setForeground(new java.awt.Color(204, 204, 255));
        employeeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeNameLabel.setText("tên");
        employeeNameLabel.setAlignmentX(0.5F);
        employeeNameLabel.setMaximumSize(new java.awt.Dimension(32000, 20));
        employeeNameLabel.setMinimumSize(new java.awt.Dimension(10, 10));
        employeeNameLabel.setPreferredSize(new java.awt.Dimension(100, 55));
        foothomePanel.add(employeeNameLabel);
        foothomePanel.add(filler4);

        logoutButton.setBackground(new java.awt.Color(51, 51, 51));
        logoutButton.setFont(new java.awt.Font("Sitka Display", 0, 20)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(204, 204, 255));
        logoutButton.setText("Đăng xuất");
        logoutButton.setAlignmentX(0.5F);
        logoutButton.setFocusPainted(false);
        logoutButton.setMaximumSize(new java.awt.Dimension(120, 30));
        logoutButton.setMinimumSize(new java.awt.Dimension(10, 10));
        logoutButton.setPreferredSize(new java.awt.Dimension(97, 55));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        foothomePanel.add(logoutButton);
        foothomePanel.add(filler2);

        homePanel.add(foothomePanel);

        mainPanel.add(homePanel);

        switchPanel.setMinimumSize(new java.awt.Dimension(400, 300));
        switchPanel.setPreferredSize(new java.awt.Dimension(550, 400));
        switchPanel.setLayout(new java.awt.CardLayout());
        switchPanel.add(employeePanel, "employee");

        introductionPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        introductionPanel.setMinimumSize(new java.awt.Dimension(500, 125));
        introductionPanel.setPreferredSize(new java.awt.Dimension(560, 125));
        switchPanel.add(introductionPanel, "introduction");
        switchPanel.add(authorPanel, "author");
        switchPanel.add(publisherPanel, "publisher");
        switchPanel.add(catogeryPanel, "catogery");
        switchPanel.add(discountPanel, "discount");
        switchPanel.add(bookPanel, "book");
        switchPanel.add(customerPanel, "customer");
        switchPanel.add(moneyBillPanel, "moneyBill");
        switchPanel.add(billPanel, "bill");
        switchPanel.add(bookEntryPanel, "bookEntry");
        switchPanel.add(settingPanel1, "setting");

        mainPanel.add(switchPanel);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void introductionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introductionButtonActionPerformed
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.introductionPanel.update();
        card.show(this.switchPanel, "introduction");
    }//GEN-LAST:event_introductionButtonActionPerformed

    private void authorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorButtonActionPerformed
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.authorPanel.reloadTable();
        card.show(this.switchPanel, "author");
    }//GEN-LAST:event_authorButtonActionPerformed

    private void publisherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherButtonActionPerformed
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.publisherPanel.reloadTable();
        card.show(this.switchPanel, "publisher"); 
    }//GEN-LAST:event_publisherButtonActionPerformed

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.catogeryPanel.reloadTable();
        card.show(this.switchPanel, "catogery");
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void employeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.employeePanel.reloadTable();
        card.show(this.switchPanel, "employee");
    }//GEN-LAST:event_employeeButtonActionPerformed

    private void discountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.discountPanel.reloadTable();
        card.show(this.switchPanel, "discount");
    }//GEN-LAST:event_discountButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.customerPanel.reloadTable();
        card.show(this.switchPanel, "customer");
    }//GEN-LAST:event_customerButtonActionPerformed

    private void moneyBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyBillButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.moneyBillPanel.reloadTable();
        card.show(this.switchPanel, "moneyBill");
    }//GEN-LAST:event_moneyBillButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.billPanel.reloadTable();
        card.show(this.switchPanel, "bill");
    }//GEN-LAST:event_billButtonActionPerformed

    private void bookEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookEntryButtonActionPerformed
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        //this.BookEntryPanel.reloadTable();
        card.show(this.switchPanel, "bookEntry");
    }//GEN-LAST:event_bookEntryButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        App.setAccount(null);
            
        Database.initialize("orcl123", Account.ADMIN_USERNAME, Account.ADMIN_PASSWORD);
        Database.connect();
        
        this.dispose();
        
        Entry entry = new Entry();
        entry.show();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void settingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingButtonActionPerformed
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        card.show(this.switchPanel, "setting"); 
    }//GEN-LAST:event_settingButtonActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)this.switchPanel.getLayout();
        this.bookPanel.reloadTable();
        card.show(this.switchPanel, "book");
    }//GEN-LAST:event_bookButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bookstore.ui.controls.MetroButton authorButton;
    private bookstore.ui.subpanel.AuthorPanel authorPanel;
    private bookstore.ui.controls.MetroButton billButton;
    private bookstore.ui.subpanel.BillPanel billPanel;
    private javax.swing.JPanel bodyhomePanel;
    private metro.MetroButton bookButton;
    private bookstore.ui.controls.MetroButton bookEntryButton;
    private bookstore.ui.subpanel.BookEntryPanel bookEntryPanel;
    private bookstore.ui.subpanel.BookPanel bookPanel;
    private bookstore.ui.controls.MetroButton categoryButton;
    private bookstore.ui.subpanel.CatogeryPanel catogeryPanel;
    private bookstore.ui.controls.MetroButton customerButton;
    private bookstore.ui.subpanel.CustomerPanel customerPanel;
    private bookstore.ui.controls.MetroButton discountButton;
    private bookstore.ui.subpanel.DiscountPanel discountPanel;
    private metro.MetroButton employeeButton;
    private javax.swing.JLabel employeeNameLabel;
    private bookstore.ui.subpanel.EmployeePanel employeePanel;
    private javax.swing.JLabel employeePositionLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel foothomePanel;
    private javax.swing.JPanel headhomePanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private bookstore.ui.controls.MetroButton introductionButton;
    private bookstore.ui.subpanel.IntroductionPanel introductionPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainPanel;
    private bookstore.ui.controls.MetroButton moneyBillButton;
    private bookstore.ui.subpanel.MoneyBillPanel moneyBillPanel;
    private bookstore.ui.controls.MetroButton publisherButton;
    private bookstore.ui.subpanel.PublisherPanel publisherPanel;
    private metro.MetroButton settingButton;
    private bookstore.ui.subpanel.SettingPanel settingPanel1;
    private javax.swing.JPanel switchPanel;
    // End of variables declaration//GEN-END:variables

}
