/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.ui.controls;

/**
 *
 * @author DELL
 */

import java.awt.Font;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.border.*;


public class StatisticPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticPanel
     */
    public StatisticPanel(Color c, String topText, String botText, String iconUrl) {
        initComponents();
        
        this.imagePanel.setBackground(c);
        this.imageLabel.setBackground(c);
        this.topPanel.setBackground(c);
        this.botPanel.setBackground(c);
        this.contentPanel.setBackground(c);
        this.setBackground(c);
        
        this.imageLabel.setIcon(new ImageIcon(iconUrl));
        this.topLabel.setText(topText);
        this.botLabel.setText(botText);
    }
    
    public void setTopText(String topText){
        this.topLabel.setText(topText);
    }
    
    public void setTopFontSize(int size){
        Font f = this.topLabel.getFont();
        this.topLabel.setFont(new Font(f.getFontName(), f.getStyle(), size));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        seperatedPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        botPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        botLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(103, 196, 240));
        setPreferredSize(new java.awt.Dimension(400, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        imagePanel.setBackground(new java.awt.Color(103, 196, 240));
        imagePanel.setAlignmentY(0.5f);
        imagePanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        imagePanel.setPreferredSize(new java.awt.Dimension(20, 20));
        imagePanel.setLayout(new javax.swing.BoxLayout(imagePanel, javax.swing.BoxLayout.LINE_AXIS));

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        imagePanel.add(imageLabel);

        add(imagePanel);

        seperatedPanel.setBackground(new java.awt.Color(255, 255, 255));
        seperatedPanel.setAlignmentY(0.5f);
        seperatedPanel.setMaximumSize(new java.awt.Dimension(5, 100));
        seperatedPanel.setPreferredSize(new java.awt.Dimension(5, 20));

        javax.swing.GroupLayout seperatedPanelLayout = new javax.swing.GroupLayout(seperatedPanel);
        seperatedPanel.setLayout(seperatedPanelLayout);
        seperatedPanelLayout.setHorizontalGroup(
            seperatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        seperatedPanelLayout.setVerticalGroup(
            seperatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(seperatedPanel);

        contentPanel.setBackground(new java.awt.Color(103, 196, 240));
        contentPanel.setAlignmentY(0.5f);
        contentPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        contentPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.PAGE_AXIS));

        topPanel.setBackground(new java.awt.Color(103, 196, 240));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.LINE_AXIS));

        topLabel.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        topLabel.setForeground(new java.awt.Color(255, 255, 255));
        topLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        topLabel.setText("100");
        topLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        topLabel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        topPanel.add(topLabel);
        topPanel.add(filler1);

        contentPanel.add(topPanel);

        botPanel.setBackground(new java.awt.Color(103, 196, 240));
        botPanel.setLayout(new javax.swing.BoxLayout(botPanel, javax.swing.BoxLayout.LINE_AXIS));
        botPanel.add(filler2);

        botLabel.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        botLabel.setForeground(new java.awt.Color(255, 255, 255));
        botLabel.setText("Sách");
        botLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        botLabel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        botPanel.add(botLabel);

        contentPanel.add(botPanel);

        add(contentPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botLabel;
    private javax.swing.JPanel botPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel seperatedPanel;
    private javax.swing.JLabel topLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
