/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bookstore.ui.subpanel;

/**
 *
 * @author DELL
 */
import javax.swing.border.Border;
import java.awt.Color;
import javax.swing.BorderFactory;
import bookstore.database.tables.Author;
import javax.swing.JOptionPane;
import bookstore.exceptions.DatabasePermissonErrorException;

public class AddAuthor extends javax.swing.JFrame {

    
    protected void initialize(AuthorPanel parent){
        this.parent = parent;
        this.setLocationRelativeTo(null);
        this.idTextField.setEditable(false);
        this.idTextField.setFocusable(false);
    }
    
    public AddAuthor(AuthorPanel parent) {
        this.initComponents();
        this.initialize(parent);
        this.action = 0;
    }
    
    public AddAuthor(AuthorPanel parent, Author author){
        this.initComponents();
        this.initialize(parent);

        this.idTextField.setText(author.getId());
        this.nameTextField.setText(author.getName());
        this.addressTextField.setText(author.getAddress());
        this.lifeStoryTextField.setText(author.getLifeStory());
        this.phoneNumberTextField.setText(author.getPhoneNumber());
        this.emailTextField.setText(author.getEmail());
        this.addButton.setText("Cập nhật");
        this.action = 1;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        informationPanel = new javax.swing.JPanel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        lifeStoryTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        lifeStoryLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        choosePanel = new javax.swing.JPanel();
        addButton = new metro.MetroButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(200, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        cancelButton = new metro.MetroButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainPanel.setMinimumSize(new java.awt.Dimension(600, 500));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.PAGE_AXIS));

        informationPanel.setBackground(new java.awt.Color(255, 255, 255));
        informationPanel.setMaximumSize(new java.awt.Dimension(32767, 400));
        informationPanel.setMinimumSize(new java.awt.Dimension(200, 300));
        informationPanel.setName("Thêm tác giả"); // NOI18N
        informationPanel.setPreferredSize(new java.awt.Dimension(300, 300));

        idTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        idTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        idTextField.setPreferredSize(new java.awt.Dimension(300, 40));

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        nameTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        nameTextField.setPreferredSize(new java.awt.Dimension(300, 40));

        addressTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addressTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        addressTextField.setToolTipText("");
        addressTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        addressTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        addressTextField.setPreferredSize(new java.awt.Dimension(300, 40));

        lifeStoryTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lifeStoryTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lifeStoryTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        lifeStoryTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        lifeStoryTextField.setPreferredSize(new java.awt.Dimension(300, 40));

        phoneNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phoneNumberTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneNumberTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        phoneNumberTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        phoneNumberTextField.setPreferredSize(new java.awt.Dimension(300, 40));

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        emailTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        emailTextField.setPreferredSize(new java.awt.Dimension(300, 40));

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phoneNumberLabel.setText("Số điện thoại");
        phoneNumberLabel.setFocusable(false);
        phoneNumberLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        phoneNumberLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        phoneNumberLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        phoneNumberLabel.setRequestFocusEnabled(false);

        lifeStoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lifeStoryLabel.setText("Tiểu sử");
        lifeStoryLabel.setFocusable(false);
        lifeStoryLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        lifeStoryLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        lifeStoryLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        lifeStoryLabel.setRequestFocusEnabled(false);

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        emailLabel.setText("Email");
        emailLabel.setFocusable(false);
        emailLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        emailLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        emailLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        emailLabel.setRequestFocusEnabled(false);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addressLabel.setText("Địa chỉ");
        addressLabel.setFocusable(false);
        addressLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        addressLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        addressLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        addressLabel.setRequestFocusEnabled(false);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nameLabel.setText("Tên tác giả");
        nameLabel.setFocusable(false);
        nameLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        nameLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        nameLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        nameLabel.setRequestFocusEnabled(false);

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idLabel.setText("Mã tác giả");
        idLabel.setFocusable(false);
        idLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        idLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        idLabel.setPreferredSize(new java.awt.Dimension(200, 40));
        idLabel.setRequestFocusEnabled(false);

        org.jdesktop.layout.GroupLayout informationPanelLayout = new org.jdesktop.layout.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(informationPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(phoneNumberLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(lifeStoryLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(emailLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(addressLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(idLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED, 50, Short.MAX_VALUE)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lifeStoryTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(phoneNumberTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(idTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(addressTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(emailTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, informationPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(idTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(idLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(addressLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(addressTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lifeStoryTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lifeStoryLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(phoneNumberTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(phoneNumberLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(informationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(emailLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        mainPanel.add(informationPanel);

        choosePanel.setBackground(new java.awt.Color(255, 255, 255));
        choosePanel.setMaximumSize(new java.awt.Dimension(32000, 100));
        choosePanel.setMinimumSize(new java.awt.Dimension(150, 80));
        choosePanel.setPreferredSize(new java.awt.Dimension(152, 100));

        addButton.setBackground(new java.awt.Color(0, 0, 0));
        addButton.setText("Thêm");
        addButton.setFont(new java.awt.Font("Sogoe Ui", 1, 25)); // NOI18N
        addButton.setMaximumSize(new java.awt.Dimension(200, 100));
        addButton.setMinimumSize(new java.awt.Dimension(150, 90));
        addButton.setPreferredSize(new java.awt.Dimension(120, 50));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        choosePanel.add(addButton);
        choosePanel.add(filler1);
        choosePanel.add(filler2);

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Hủy bỏ");
        cancelButton.setActionCommand("");
        cancelButton.setFont(new java.awt.Font("Sogoe Ui", 1, 20)); // NOI18N
        cancelButton.setMaximumSize(new java.awt.Dimension(200, 90));
        cancelButton.setMinimumSize(new java.awt.Dimension(100, 50));
        cancelButton.setPreferredSize(new java.awt.Dimension(120, 50));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        choosePanel.add(cancelButton);

        mainPanel.add(choosePanel);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Author getAuthor(){
        String id = this.idTextField.getText();
        String name = this.nameTextField.getText();
        String address = this.addressTextField.getText();
        String lifestory = this.lifeStoryTextField.getText();
        String phonenumber = this.phoneNumberTextField.getText();
        String email = this.emailTextField.getText();
        return new Author(id, name, address, lifestory, phonenumber, email);
    }
    
    private void addAuthor(Author author){
        if (author.getName().isEmpty() 
            || author.getAddress().isEmpty()
            || author.getLifeStory().isEmpty()
            || author.getPhoneNumber().isEmpty()
            || author.getEmail().isEmpty()
        ){
            JOptionPane.showMessageDialog(null, "Bạn cần nhập đầy đủ thông tin.", "Nhập thông tin", 1);
        }
        else{
            try{
                if (Author.insert(author)){
                    JOptionPane.showMessageDialog(null, "Dữ liệu đã được thêm.", "Thêm tác giả", 1);
                    this.parent.reloadTable();
                }
                else 
                    JOptionPane.showMessageDialog(null, "Dữ liệu không được thêm.", "Lỗi thêm tác giả", 1);
            }catch(DatabasePermissonErrorException ex){
                    JOptionPane.showMessageDialog(null,
                        "Bạn không có quyền thêm dữ liệu này.",
                        "Lỗi", JOptionPane.WARNING_MESSAGE);             
            }
        }
    }

    
    private void updateAuthor(Author author){
        if (author.getName().isEmpty() 
            || author.getAddress().isEmpty()
            || author.getLifeStory().isEmpty()
            || author.getPhoneNumber().isEmpty()
            || author.getEmail().isEmpty()
        ){
            JOptionPane.showMessageDialog(null, "Bạn cần nhập đầy đủ thông tin.", "Nhập thông tin", 1);
        }
        else{
            try{
                if(Author.update(author)){
                    JOptionPane.showMessageDialog(
                        null,
                        "Dữ liệu đã được cập nhật.",
                        "Cập nhật tác giả",
                        1
                    );
                    this.parent.reloadTable();
                }
                else{
                    JOptionPane.showMessageDialog(
                        null,
                        "Dữ liệu không cập nhật được",
                        "Lỗi cập nhật",
                        1
                    );
                }
            }catch(DatabasePermissonErrorException ex){
                    JOptionPane.showMessageDialog(null,
                    "Bạn không có quyền sửa dữ liệu này.",
                    "Lỗi", JOptionPane.WARNING_MESSAGE);
                    
            
            }
        }
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try{
            Author author = this.getAuthor();

            if(this.action == 0){
                this.addAuthor(author);
            }
            else if(this.action == 1){
                this.updateAuthor(author);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(
                null,
                "Có lỗi xảy ra:" + e.getMessage(),
                "Thông báo.",
                1
            );
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private metro.MetroButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private metro.MetroButton cancelButton;
    private javax.swing.JPanel choosePanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JLabel lifeStoryLabel;
    private javax.swing.JTextField lifeStoryTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    // End of variables declaration//GEN-END:variables
    private int action;
    private AuthorPanel parent;
}
