
package bookstore.ui.subpanel;

/**
 *
 * @author DELL
 */

import bookstore.utils.Formatter;
import bookstore.database.tables.*;
import bookstore.database.Database;
import bookstore.exceptions.DatabasePermissonErrorException;
import bookstore.ui.controls.*;
import java.awt.Color;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;

public final class IntroductionPanel extends javax.swing.JPanel {

    /**
     * Creates new form Introduction
     */
    public IntroductionPanel() throws DatabasePermissonErrorException {
        initComponents();
        
        this.numberOfBooksPanel = new StatisticPanel(
                new Color(103, 196, 240), 
                "", 
                "Sách", 
                "D:\\UIT\\Lap trinh java\\bookstore\\imgs\\book3.png"
        );
        this.leftTopPanel.add(this.numberOfBooksPanel);
        
        this.numberOfAuthorsPanel = new StatisticPanel(
                new Color(121, 195, 70), 
                "", 
                "Tác giả", 
                "D:\\UIT\\Lap trinh java\\bookstore\\imgs\\author.png"
        );
        this.middleTopPanel.add(this.numberOfAuthorsPanel);

        this.numberOfPublishersPanel = new StatisticPanel(
                new Color(96, 100, 191), 
                "", 
                "Nhà xuất bản", 
                "D:\\UIT\\Lap trinh java\\bookstore\\imgs\\publisher.png"
        );
        this.rightTopPanel.add(this.numberOfPublishersPanel);
        
        this.numberOfCustomersPanel = new StatisticPanel(
                new Color(255, 85, 85), 
                "", 
                "Khách hàng", 
                "D:\\UIT\\Lap trinh java\\bookstore\\imgs\\customer.png"
        );        
        this.leftBottomPanel.add(this.numberOfCustomersPanel);
        
        this.numberOfEmployeePanel = new StatisticPanel(
                new Color(2, 101, 165), 
                "", 
                "Nhân viên", 
                "D:\\UIT\\Lap trinh java\\bookstore\\imgs\\employee .png"
        );       
       
        this.middleBottomPanel.add(this.numberOfEmployeePanel);
        
        this.numberOfCategoryPanel = new StatisticPanel(
                new Color(47, 53, 65), 
                "", 
                "Thể loại", 
                "D:\\UIT\\Lap trinh java\\bookstore\\imgs\\category.png"
        );
       
        this.rightBottomPanel.add(this.numberOfCategoryPanel);
        
        this.update();
    }
    
    public void update(){
        try{
            int numberOfBooks = Book.countBook();
            this.numberOfBooksPanel.setTopText(String.valueOf(numberOfBooks));

            int numberOfAuthors = Author.countAuthor();
            this.numberOfAuthorsPanel.setTopText(String.valueOf(numberOfAuthors));

            int numberOfPublishers = Publisher.countPublisher();
            this.numberOfPublishersPanel.setTopText(String.valueOf(numberOfPublishers));

            int numberOfCustomers = Customer.countCustomer();
            this.numberOfCustomersPanel.setTopText(String.valueOf(numberOfCustomers));

            int numberOfEmployees = Employee.countEmployee();
            this.numberOfEmployeePanel.setTopText(String.valueOf(numberOfEmployees));

            int numberOfCategorys = Category.countCategory();
            this.numberOfCategoryPanel.setTopText(String.valueOf(numberOfCategorys));
        }
        catch (Exception e){
            System.out.println(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        inputPanel = new javax.swing.JPanel();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(70, 32767));
        monthLabel = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        monthorYearTextField = new javax.swing.JTextField();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jPanel1 = new javax.swing.JPanel();
        generateReportButton = new javax.swing.JButton();
        topsachReportButton = new javax.swing.JButton();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        generateReportButton1 = new javax.swing.JButton();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        generateReportButton2 = new javax.swing.JButton();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 100));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 50));
        topPanel = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        leftTopPanel = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        middleTopPanel = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        rightTopPanel = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 20));
        bottomPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        leftBottomPanel = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        middleBottomPanel = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        rightBottomPanel = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 50));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(20000, 32000));
        setMinimumSize(new java.awt.Dimension(200, 100));
        setPreferredSize(new java.awt.Dimension(560, 100));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        titlePanel.setMinimumSize(new java.awt.Dimension(0, 90));

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("QUẢN LÍ BÁO CÁO, THỐNG KÊ CỦA NHÀ SÁCH LUCKY");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        add(titlePanel);

        reportPanel.setBackground(new java.awt.Color(255, 255, 255));
        reportPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        reportPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        reportPanel.setLayout(new javax.swing.BoxLayout(reportPanel, javax.swing.BoxLayout.LINE_AXIS));

        filler12.setBackground(new java.awt.Color(228, 241, 254));
        reportPanel.add(filler12);

        inputPanel.setBackground(new java.awt.Color(255, 255, 255));
        inputPanel.setMaximumSize(new java.awt.Dimension(32000, 100));
        inputPanel.setMinimumSize(new java.awt.Dimension(215, 50));
        inputPanel.setPreferredSize(new java.awt.Dimension(185, 50));
        inputPanel.setLayout(new javax.swing.BoxLayout(inputPanel, javax.swing.BoxLayout.LINE_AXIS));
        inputPanel.add(filler19);

        monthLabel.setBackground(new java.awt.Color(0, 0, 0));
        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        monthLabel.setText("Tháng/Năm");
        inputPanel.add(monthLabel);
        inputPanel.add(filler14);

        monthorYearTextField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        monthorYearTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        monthorYearTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        monthorYearTextField.setMaximumSize(new java.awt.Dimension(32000, 40));
        monthorYearTextField.setMinimumSize(new java.awt.Dimension(7, 10));
        monthorYearTextField.setPreferredSize(new java.awt.Dimension(7, 10));
        inputPanel.add(monthorYearTextField);
        inputPanel.add(filler21);

        reportPanel.add(inputPanel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(3200, 3200));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 10));
        jPanel1.setRequestFocusEnabled(false);

        generateReportButton.setBackground(new java.awt.Color(0, 0, 0));
        generateReportButton.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        generateReportButton.setForeground(new java.awt.Color(255, 255, 255));
        generateReportButton.setText("Báo cáo doanh thu theo năm");
        generateReportButton.setAlignmentX(0.5F);
        generateReportButton.setMaximumSize(new java.awt.Dimension(32000, 50));
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });

        topsachReportButton.setBackground(new java.awt.Color(0, 0, 0));
        topsachReportButton.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        topsachReportButton.setForeground(new java.awt.Color(255, 255, 255));
        topsachReportButton.setText("Sách bán chạy theo tháng");
        topsachReportButton.setAlignmentX(0.5F);
        topsachReportButton.setMaximumSize(new java.awt.Dimension(32000, 50));
        topsachReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topsachReportButtonActionPerformed(evt);
            }
        });

        generateReportButton1.setBackground(new java.awt.Color(0, 0, 0));
        generateReportButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        generateReportButton1.setForeground(new java.awt.Color(255, 255, 255));
        generateReportButton1.setText("Báo cáo tồn kho");
        generateReportButton1.setAlignmentX(0.5F);
        generateReportButton1.setMaximumSize(new java.awt.Dimension(32000, 50));
        generateReportButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButton1ActionPerformed(evt);
            }
        });

        generateReportButton2.setBackground(new java.awt.Color(0, 0, 0));
        generateReportButton2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        generateReportButton2.setForeground(new java.awt.Color(255, 255, 255));
        generateReportButton2.setText("Báo cáo công nợ ");
        generateReportButton2.setAlignmentX(0.5F);
        generateReportButton2.setMaximumSize(new java.awt.Dimension(32000, 50));
        generateReportButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generateReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topsachReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(filler20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filler17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateReportButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateReportButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(filler16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReportButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topsachReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(filler17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(filler15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        reportPanel.add(jPanel1);
        reportPanel.add(filler18);

        add(reportPanel);
        add(filler3);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setMaximumSize(new java.awt.Dimension(10000, 200));
        topPanel.setPreferredSize(new java.awt.Dimension(150, 200));
        topPanel.setLayout(new javax.swing.BoxLayout(topPanel, javax.swing.BoxLayout.LINE_AXIS));
        topPanel.add(filler11);

        leftTopPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        leftTopPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        leftTopPanel.setLayout(new javax.swing.BoxLayout(leftTopPanel, javax.swing.BoxLayout.LINE_AXIS));
        topPanel.add(leftTopPanel);
        topPanel.add(filler10);

        middleTopPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        middleTopPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        middleTopPanel.setLayout(new javax.swing.BoxLayout(middleTopPanel, javax.swing.BoxLayout.LINE_AXIS));
        topPanel.add(middleTopPanel);
        topPanel.add(filler9);

        rightTopPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        rightTopPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        rightTopPanel.setLayout(new javax.swing.BoxLayout(rightTopPanel, javax.swing.BoxLayout.LINE_AXIS));
        topPanel.add(rightTopPanel);
        topPanel.add(filler8);

        add(topPanel);
        add(filler1);
        add(filler13);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setMaximumSize(new java.awt.Dimension(10000, 200));
        bottomPanel.setPreferredSize(new java.awt.Dimension(150, 200));
        bottomPanel.setLayout(new javax.swing.BoxLayout(bottomPanel, javax.swing.BoxLayout.LINE_AXIS));
        bottomPanel.add(filler4);

        leftBottomPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        leftBottomPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        leftBottomPanel.setLayout(new javax.swing.BoxLayout(leftBottomPanel, javax.swing.BoxLayout.LINE_AXIS));
        bottomPanel.add(leftBottomPanel);
        bottomPanel.add(filler6);

        middleBottomPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        middleBottomPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        middleBottomPanel.setLayout(new javax.swing.BoxLayout(middleBottomPanel, javax.swing.BoxLayout.LINE_AXIS));
        bottomPanel.add(middleBottomPanel);
        bottomPanel.add(filler7);

        rightBottomPanel.setMaximumSize(new java.awt.Dimension(32000, 32000));
        rightBottomPanel.setPreferredSize(new java.awt.Dimension(40, 40));
        rightBottomPanel.setLayout(new javax.swing.BoxLayout(rightBottomPanel, javax.swing.BoxLayout.LINE_AXIS));
        bottomPanel.add(rightBottomPanel);
        bottomPanel.add(filler5);

        add(bottomPanel);
        add(filler2);
    }// </editor-fold>//GEN-END:initComponents

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButtonActionPerformed
        try {  
            JasperDesign jd = JRXmlLoader.load(
                    "D:\\ireport\\total_monthly_bill.jrxml"
            );
            JasperReport jr = JasperCompileManager.compileReport(
                    "D:\\ireport\\total_monthly_bill.jrxml"
            );
            
            HashMap hm = new HashMap();
            hm.put("year from NgayHD", this.monthorYearTextField.getText());
            
            JasperPrint jp = JasperFillManager.fillReport(jr, hm, Database.connection());
            JasperViewer.viewReport(jp, false);
            
            java.text.SimpleDateFormat sdm = new java.text.SimpleDateFormat("dd MM yyyy hh mm ss");
            
            String fileName = "report " + sdm.format(new java.util.Date()) + ".pdf"; 
            
            JasperExportManager.exportReportToPdfFile(
                jp, "D:\\UIT\\Lap trinh java\\bookstore\\report\\" + fileName
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot show report" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateReportButtonActionPerformed

    private void topsachReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topsachReportButtonActionPerformed
        try {  
            JasperDesign jd = JRXmlLoader.load(
                    "D:\\ireport\\best_selling_book.jrxml"
            );
            JasperReport jr = JasperCompileManager.compileReport(
                    "D:\\ireport\\best_selling_book.jrxml"
            );
            HashMap hm = new HashMap();
            hm.put("Month from NgayHD", this.monthorYearTextField.getText());
            
            Connection conn = Database.connection();
            conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            //conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            JasperPrint jp = JasperFillManager.fillReport(jr, hm, conn);
            JasperViewer.viewReport(jp, false);
            
            java.text.SimpleDateFormat sdm = new java.text.SimpleDateFormat("dd MM yyyy hh mm ss");
            
            String fileName = "report " + sdm.format(new java.util.Date()) + ".pdf"; 
            
            JasperExportManager.exportReportToPdfFile(
                jp, "D:\\UIT\\Lap trinh java\\bookstore\\report\\" + fileName
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot show report" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_topsachReportButtonActionPerformed

    private void generateReportButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButton1ActionPerformed
        try {  
            JasperDesign jd = JRXmlLoader.load(
                    "D:\\ireport\\tonkho.jrxml"
            );
            JasperReport jr = JasperCompileManager.compileReport(
                    "D:\\ireport\\tonkho.jrxml"
            );
            
            HashMap hm = new HashMap();
            hm.put("month", Integer.valueOf(this.monthorYearTextField.getText()));
            
            JasperPrint jp = JasperFillManager.fillReport(jr, hm, Database.connection());
            JasperViewer.viewReport(jp, false);
            
            java.text.SimpleDateFormat sdm = new java.text.SimpleDateFormat("dd MM yyyy hh mm ss");
            
            String fileName = "report " + sdm.format(new java.util.Date()) + ".pdf"; 
            
            JasperExportManager.exportReportToPdfFile(
                jp, "D:\\UIT\\Lap trinh java\\bookstore\\report\\" + fileName
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot show report" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateReportButton1ActionPerformed

    private void generateReportButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButton2ActionPerformed
        try {  
            JasperDesign jd = JRXmlLoader.load(
                    "D:\\ireport\\baocaocongno.jrxml"
            );
            JasperReport jr = JasperCompileManager.compileReport(
                    "D:\\ireport\\baocaocongno.jrxml"
            );
            
            HashMap hm = new HashMap();
            hm.put("month", Integer.valueOf(this.monthorYearTextField.getText()));
            
            JasperPrint jp = JasperFillManager.fillReport(jr, hm, Database.connection());
            JasperViewer.viewReport(jp, false);
            
            java.text.SimpleDateFormat sdm = new java.text.SimpleDateFormat("dd MM yyyy hh mm ss");
            
            String fileName = "report " + sdm.format(new java.util.Date()) + ".pdf"; 
            
            JasperExportManager.exportReportToPdfFile(
                jp, "D:\\UIT\\Lap trinh java\\bookstore\\report\\" + fileName
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot show report" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateReportButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JButton generateReportButton1;
    private javax.swing.JButton generateReportButton2;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftBottomPanel;
    private javax.swing.JPanel leftTopPanel;
    private javax.swing.JPanel middleBottomPanel;
    private javax.swing.JPanel middleTopPanel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthorYearTextField;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JPanel rightBottomPanel;
    private javax.swing.JPanel rightTopPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton topsachReportButton;
    // End of variables declaration//GEN-END:variables
    private StatisticPanel numberOfBooksPanel;
    private StatisticPanel numberOfAuthorsPanel;
    private StatisticPanel numberOfPublishersPanel;
    private StatisticPanel numberOfCustomersPanel;
    private StatisticPanel numberOfEmployeePanel;
    private StatisticPanel numberOfCategoryPanel;
}
